# Generated by Django 4.1.3 on 2022-11-18 03:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subsc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None)),
                ('price', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
                ('subsc_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Rent_app.subsc_directory')),
            ],
        ),
    ]
